// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpSAa_i9Wa9PILosV7rTowApwcH25HbQ',
    appId: '1:911226746962:web:84053e085ebafe1ab4478b',
    messagingSenderId: '911226746962',
    projectId: 'fir-connect-8138b',
    authDomain: 'fir-connect-8138b.firebaseapp.com',
    databaseURL: 'https://fir-connect-8138b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connect-8138b.firebasestorage.app',
    measurementId: 'G-X1TCMYXPVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLCuwwSZuQASzpVT4G7HMePI7PC4OIQs',
    appId: '1:911226746962:android:7fa682eb994a3f7cb4478b',
    messagingSenderId: '911226746962',
    projectId: 'fir-connect-8138b',
    databaseURL: 'https://fir-connect-8138b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connect-8138b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLgKKKDF37vGsAbdJj5NSdRKmtkI16rYk',
    appId: '1:911226746962:ios:df025ef7d89c1115b4478b',
    messagingSenderId: '911226746962',
    projectId: 'fir-connect-8138b',
    databaseURL: 'https://fir-connect-8138b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connect-8138b.firebasestorage.app',
    iosBundleId: 'com.example.flavorQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLgKKKDF37vGsAbdJj5NSdRKmtkI16rYk',
    appId: '1:911226746962:ios:df025ef7d89c1115b4478b',
    messagingSenderId: '911226746962',
    projectId: 'fir-connect-8138b',
    databaseURL: 'https://fir-connect-8138b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connect-8138b.firebasestorage.app',
    iosBundleId: 'com.example.flavorQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDpSAa_i9Wa9PILosV7rTowApwcH25HbQ',
    appId: '1:911226746962:web:4577a58e984b3129b4478b',
    messagingSenderId: '911226746962',
    projectId: 'fir-connect-8138b',
    authDomain: 'fir-connect-8138b.firebaseapp.com',
    databaseURL: 'https://fir-connect-8138b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connect-8138b.firebasestorage.app',
    measurementId: 'G-6GP7TJR0D3',
  );
}
